// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjw_d3_maUWqEwPxVVoB8Zrc8aF0hWNCI',
    appId: '1:283076267267:web:bc6c5c7872cdcfd988ad36',
    messagingSenderId: '283076267267',
    projectId: 'multibranch-692b7',
    authDomain: 'multibranch-692b7.firebaseapp.com',
    storageBucket: 'multibranch-692b7.firebasestorage.app',
    measurementId: 'G-CL6F9KSP6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtQKkOhMO2iYngDrg5rvMP7mjs1j6vv5Y',
    appId: '1:283076267267:android:c12436d83e0ce5c088ad36',
    messagingSenderId: '283076267267',
    projectId: 'multibranch-692b7',
    storageBucket: 'multibranch-692b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVkh-oYxasiRp7eCDVD188hnxc3lVn9Ts',
    appId: '1:283076267267:ios:91ad356bd9daa9ed88ad36',
    messagingSenderId: '283076267267',
    projectId: 'multibranch-692b7',
    storageBucket: 'multibranch-692b7.firebasestorage.app',
    iosBundleId: 'com.example.flutterMultibranchProyect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVkh-oYxasiRp7eCDVD188hnxc3lVn9Ts',
    appId: '1:283076267267:ios:91ad356bd9daa9ed88ad36',
    messagingSenderId: '283076267267',
    projectId: 'multibranch-692b7',
    storageBucket: 'multibranch-692b7.firebasestorage.app',
    iosBundleId: 'com.example.flutterMultibranchProyect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjw_d3_maUWqEwPxVVoB8Zrc8aF0hWNCI',
    appId: '1:283076267267:web:ebd7294df6f1117588ad36',
    messagingSenderId: '283076267267',
    projectId: 'multibranch-692b7',
    authDomain: 'multibranch-692b7.firebaseapp.com',
    storageBucket: 'multibranch-692b7.firebasestorage.app',
    measurementId: 'G-Y2RBDP9HYF',
  );
}
